IBM/javacore-analyser

- javacore_analyzer.py
> Fixes #6 Removing copied or extracted javacores dir

- CONTRIBUTING.md
- MAINTAINERS.md
- README.md
- REQUIREMENTS.md
Fixes #4 :
I made the following changes:
1. Added steps in README how to run the tool
2. In Contributing fixed links, added steps for developers how to run the tool from Pycharm and how to test it and added code style guidance
> 4 finish the documentation

- verbose_gc.py
> 34 adding closing tag should be set with debug level

- javacore_set.py
- test/test_javacore_set.py
> System information xmx value is blank when xmx does not have units 

- templates/index.html
Fixes #28 
This is my proposed ui:
> Fix #28 Simplify web

- src/javacore_analyser/javacore_analyser_batch.py
> Updated the input/output arguments of the javacore_analyser_batch.

- README.md
- src/javacore_analyser/__main__.py
- src/javacore_analyser/javacore_analyser_batch.py
- src/javacore_analyser/javacore_analyser_web.py
Fixes #79
This pull requests allows you run the application as a module. You can test it in the following way:
```
pip install .   
python -m javacore_analyser -h
```
> Create _main_ class

- src/javacore_analyser/javacore_analyser_batch.py
Fixes #69
I do not have Windows to test this, but this should already resolve the issue. Can you try this?
> Fixes #69 use normpath for paths.

- src/javacore_analyser/data/html/error.html
- src/javacore_analyser/javacore_analyser_batch.py
- test/test_javacore_analyser.py
Fixes #87
This pull request sets index.html page with error message plus stack trace if processing fails.
> 87-better-logging-when-processing-is-failing

- src/javacore_analyser/javacore_set.py
> Fixes #101 - improve the message regarding generating placeholder htmls

- src/javacore_analyser/verbose_gc.py
- test/data/javacores/verbosegc.230420.33424.txt.001
Fixes #107 
@PiotrAniola82 I have created a fix for performance of verbose gc we were talking about.
> #107 Improve performance of processing verbose gc files.

- requirements.txt
> #115 Test pull request

- src/javacore_analyser/data/jquery/wait2scripts.js
> #97 Changed the way how the data are fetched (from innerHTML to innerText) and condition to add only numbers was added.

- src/javacore_analyser/data/xml/report.xsl
- src/javacore_analyser/data/xml/threads/thread.xsl
- src/javacore_analyser/java_thread.py
- src/javacore_analyser/thread_snapshot.py
- test/test_thread_snapshot.py
> #106 Add the address of the thread in the thread name

- Dockerfile
Fixes #117 
This is only refactor.
> Fixes #117 Add brackets to ARG in Dockerfile

- src/javacore_analyser/data/xml/report.xsl
- src/javacore_analyser/tips.py
> Fixes #121 Replace the wait name with javacore analyser in the code

- src/javacore_analyser/data/style.js
- src/javacore_analyser/javacore_analyser_web.py
- src/javacore_analyser/templates/index.html
> #24 main page style

- README.md
> #140 Add to the documention option to use volumes for containers.

- src/javacore_analyser/javacore_analyser_batch.py
- src/javacore_analyser/javacore_analyser_web.py
> #144 Add documentation for few methods.

- .travis.yml
> #154 Generate pip package for all branches

- src/javacore_analyser/javacore.py
- test/test_javacore.py
- test/test_javacore_analyser.py
> #156 LookupError-unknown-encoding-available
